drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SSrvc;
drop table Srvc cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SSubj;
drop table Subj cascade constraints;
drop sequence SCrtBnkCMD;
drop table CrtBnkCMD cascade constraints;
drop sequence SBnk;
drop table Bnk cascade constraints;
drop sequence SAccnt;
drop table Accnt cascade constraints;
drop sequence SChngNmCMD;
drop table ChngNmCMD cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SCrtAccntCMD;
drop table CrtAccntCMD cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SAdmnstrtrBnks;
drop table AdmnstrtrBnks cascade constraints;
drop sequence SBnkCrtr;
drop table BnkCrtr cascade constraints;
drop sequence SCrrnc;
drop table Crrnc cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SSubjObs;
drop table SubjObs cascade constraints;
drop sequence SBnkAccnts;
drop table BnkAccnts cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SAdmnstrtrBnksObs;
drop table AdmnstrtrBnksObs cascade constraints;
