package model.meta;

public interface DebitTransferNotExecutedMssgsVisitor extends DebitTransferNotExecutedDOWNMssgsVisitor, DebitTransferNotExecutedUPMssgsVisitor {}


interface DebitTransferNotExecutedDOWNMssgsVisitor  {

    public void handleDebitTransferNotExecutedAddDebitTransferTransactionMssg(DebitTransferNotExecutedAddDebitTransferTransactionMssg event) throws persistence.PersistenceException;
    public void handleDebitTransferNotExecutedRemoveDebitTransferTransactionMssg(DebitTransferNotExecutedRemoveDebitTransferTransactionMssg event) throws persistence.PersistenceException;
    
}


interface DebitTransferNotExecutedUPMssgsVisitor  {

    public void handleDebitTransferNotExecutedAddDebitTransferTransactionMssg(DebitTransferNotExecutedAddDebitTransferTransactionMssg event) throws persistence.PersistenceException;
    public void handleDebitTransferNotExecutedRemoveDebitTransferTransactionMssg(DebitTransferNotExecutedRemoveDebitTransferTransactionMssg event) throws persistence.PersistenceException;
    
}
