package model.meta;

public interface DebitTransferSuccessfulMssgsVisitor extends DebitTransferSuccessfulDOWNMssgsVisitor, DebitTransferSuccessfulUPMssgsVisitor {}


interface DebitTransferSuccessfulDOWNMssgsVisitor  {

    public void handleDebitTransferSuccessfulAddDebitTransferTransactionMssg(DebitTransferSuccessfulAddDebitTransferTransactionMssg event) throws persistence.PersistenceException;
    public void handleDebitTransferSuccessfulRemoveDebitTransferTransactionMssg(DebitTransferSuccessfulRemoveDebitTransferTransactionMssg event) throws persistence.PersistenceException;
    
}


interface DebitTransferSuccessfulUPMssgsVisitor  {

    public void handleDebitTransferSuccessfulAddDebitTransferTransactionMssg(DebitTransferSuccessfulAddDebitTransferTransactionMssg event) throws persistence.PersistenceException;
    public void handleDebitTransferSuccessfulRemoveDebitTransferTransactionMssg(DebitTransferSuccessfulRemoveDebitTransferTransactionMssg event) throws persistence.PersistenceException;
    
}
