drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SSrvc;
drop table Srvc cascade constraints;
drop sequence SAccntRcvdGrnt;
drop table AccntRcvdGrnt cascade constraints;
drop sequence SSubj;
drop table Subj cascade constraints;
drop sequence SDebiTrfTran;
drop table DebiTrfTran cascade constraints;
drop sequence SAccntGrntdGrnt;
drop table AccntGrntdGrnt cascade constraints;
drop sequence SChngNmCMD;
drop table ChngNmCMD cascade constraints;
drop sequence SDebiTraStat;
drop table DebiTraStat cascade constraints;
drop sequence SStrnStt;
drop table StrnStt cascade constraints;
drop sequence SCrrncMngr;
drop table CrrncMngr cascade constraints;
drop sequence SDebTransLst;
drop table DebTransLst cascade constraints;
drop sequence SCrtAccntCMD;
drop table CrtAccntCMD cascade constraints;
drop sequence SIntrnlF;
drop table IntrnlF cascade constraints;
drop sequence SBlnVl;
drop table BlnVl cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SChngRcvrBnkCMD;
drop table ChngRcvrBnkCMD cascade constraints;
drop sequence SPrcnt;
drop table Prcnt cascade constraints;
drop sequence SAccntSrvcTmplt;
drop table AccntSrvcTmplt cascade constraints;
drop sequence SCrrnc;
drop table Crrnc cascade constraints;
drop sequence SAmnt;
drop table Amnt cascade constraints;
drop sequence SAccntMn2;
drop table AccntMn2 cascade constraints;
drop sequence SCrtBnkCMD;
drop table CrtBnkCMD cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SDbTrNtTmpl;
drop table DbTrNtTmpl cascade constraints;
drop sequence SCrtDbtGrntCMD;
drop table CrtDbtGrntCMD cascade constraints;
drop sequence SExctCMD;
drop table ExctCMD cascade constraints;
drop sequence SAdmnstrtrBnks;
drop table AdmnstrtrBnks cascade constraints;
drop sequence SAccntSrvcSccssfl;
drop table AccntSrvcSccssfl cascade constraints;
drop sequence SLmtAccnt;
drop table LmtAccnt cascade constraints;
drop sequence SChngRcvAccCMD;
drop table ChngRcvAccCMD cascade constraints;
drop sequence SDbtGrntLst;
drop table DbtGrntLst cascade constraints;
drop sequence SAccntPx;
drop table AccntPx cascade constraints;
drop sequence STrnsctnF;
drop table TrnsctnF cascade constraints;
drop sequence SAccnt;
drop table Accnt cascade constraints;
drop sequence SAdmnstrtrCrrncMngr;
drop table AdmnstrtrCrrncMngr cascade constraints;
drop sequence SUsTmpltCMD;
drop table UsTmpltCMD cascade constraints;
drop sequence SDbTrNtExec;
drop table DbTrNtExec cascade constraints;
drop sequence SChngCrrncCMD;
drop table ChngCrrncCMD cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SLmtTp;
drop table LmtTp cascade constraints;
drop sequence SAccntDebTrfTrans;
drop table AccntDebTrfTrans cascade constraints;
drop sequence SChngMnCMD;
drop table ChngMnCMD cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SMn;
drop table Mn cascade constraints;
drop sequence SBnk;
drop table Bnk cascade constraints;
drop sequence SDbtTrnSucc;
drop table DbtTrnSucc cascade constraints;
drop sequence SAccntSrvcNtExctd;
drop table AccntSrvcNtExctd cascade constraints;
drop sequence SDbtGrnt;
drop table DbtGrnt cascade constraints;
drop sequence SBnkCrtr;
drop table BnkCrtr cascade constraints;
drop sequence SSubjObs;
drop table SubjObs cascade constraints;
drop sequence SCrrncMngrExchngRts;
drop table CrrncMngrExchngRts cascade constraints;
drop sequence SCrrncMngrCrrncStck;
drop table CrrncMngrCrrncStck cascade constraints;
drop sequence SDebTransLstDbtTrnsfrs;
drop table DebTransLstDbtTrnsfrs cascade constraints;
drop sequence SDbTrNtTmplTmplts;
drop table DbTrNtTmplTmplts cascade constraints;
drop sequence SAdmnstrtrBnksObs;
drop table AdmnstrtrBnksObs cascade constraints;
drop sequence SDbtGrntLstDbtGrnts;
drop table DbtGrntLstDbtGrnts cascade constraints;
drop sequence SDbTrNtExecNtExctds;
drop table DbTrNtExecNtExctds cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SAccntDebTrfTransObs;
drop table AccntDebTrfTransObs cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SBnkAccnts;
drop table BnkAccnts cascade constraints;
drop sequence SDbtTrnSuccSccssfls;
drop table DbtTrnSuccSccssfls cascade constraints;
