drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SSrvc;
drop table Srvc cascade constraints;
drop sequence SCmpnstn;
drop table Cmpnstn cascade constraints;
drop sequence SAccntRcvdGrnt;
drop table AccntRcvdGrnt cascade constraints;
drop sequence SDebiTrfTran;
drop table DebiTrfTran cascade constraints;
drop sequence SSubj;
drop table Subj cascade constraints;
drop sequence SChngNmCMD;
drop table ChngNmCMD cascade constraints;
drop sequence SDebiTraStat;
drop table DebiTraStat cascade constraints;
drop sequence SDebTransLst;
drop table DebTransLst cascade constraints;
drop sequence SCrrncMngr;
drop table CrrncMngr cascade constraints;
drop sequence SBlnVl;
drop table BlnVl cascade constraints;
drop sequence SPrcnt;
drop table Prcnt cascade constraints;
drop sequence SExchngRtWrp;
drop table ExchngRtWrp cascade constraints;
drop sequence SCrrnc;
drop table Crrnc cascade constraints;
drop sequence SExctCmpnstnCMD;
drop table ExctCmpnstnCMD cascade constraints;
drop sequence SBankOwAccPx;
drop table BankOwAccPx cascade constraints;
drop sequence SChngSbjctCMD;
drop table ChngSbjctCMD cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SDbTrNtTmpl;
drop table DbTrNtTmpl cascade constraints;
drop sequence SCrtDbtGrntCMD;
drop table CrtDbtGrntCMD cascade constraints;
drop sequence STrggrLst;
drop table TrggrLst cascade constraints;
drop sequence SExctCMD;
drop table ExctCMD cascade constraints;
drop sequence SAccntSrvcSccssfl;
drop table AccntSrvcSccssfl cascade constraints;
drop sequence SChngRcvAccCMD;
drop table ChngRcvAccCMD cascade constraints;
drop sequence SCmpnstnRqst;
drop table CmpnstnRqst cascade constraints;
drop sequence SAccntAllCmpnstn;
drop table AccntAllCmpnstn cascade constraints;
drop sequence SAccntPx;
drop table AccntPx cascade constraints;
drop sequence STrnsctnF;
drop table TrnsctnF cascade constraints;
drop sequence SNDbtTrnsfr;
drop table NDbtTrnsfr cascade constraints;
drop sequence SAdmnstrtrCrrncMngr;
drop table AdmnstrtrCrrncMngr cascade constraints;
drop sequence SUsTmpltCMD;
drop table UsTmpltCMD cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SAccntDebTrfTrans;
drop table AccntDebTrfTrans cascade constraints;
drop sequence SChngMnCMD;
drop table ChngMnCMD cascade constraints;
drop sequence SCmpReqSt;
drop table CmpReqSt cascade constraints;
drop sequence SMn;
drop table Mn cascade constraints;
drop sequence STrggrVl;
drop table TrggrVl cascade constraints;
drop sequence SAllCmpLstOutgngCmps;
drop table AllCmpLstOutgngCmps cascade constraints;
drop sequence SAccntSrvcNtExctd;
drop table AccntSrvcNtExctd cascade constraints;
drop sequence SDbtGrnt;
drop table DbtGrnt cascade constraints;
drop sequence SBnkCrtr;
drop table BnkCrtr cascade constraints;
drop sequence SAllCmpLst;
drop table AllCmpLst cascade constraints;
drop sequence SAccntGrntdGrnt;
drop table AccntGrntdGrnt cascade constraints;
drop sequence SCrtAccntCMD;
drop table CrtAccntCMD cascade constraints;
drop sequence SIntrnlF;
drop table IntrnlF cascade constraints;
drop sequence SDebTraStaDo;
drop table DebTraStaDo cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SChngRcvrBnkCMD;
drop table ChngRcvrBnkCMD cascade constraints;
drop sequence SAccntSrvcTmplt;
drop table AccntSrvcTmplt cascade constraints;
drop sequence SAmnt;
drop table Amnt cascade constraints;
drop sequence SCrtBnkCMD;
drop table CrtBnkCMD cascade constraints;
drop sequence SCmpnstnStt;
drop table CmpnstnStt cascade constraints;
drop sequence SBnkPx;
drop table BnkPx cascade constraints;
drop sequence SCmpnstnPndngRqsts;
drop table CmpnstnPndngRqsts cascade constraints;
drop sequence SAdmnstrtrBnks;
drop table AdmnstrtrBnks cascade constraints;
drop sequence SLmtAccnt;
drop table LmtAccnt cascade constraints;
drop sequence SCmpDeclndCMD;
drop table CmpDeclndCMD cascade constraints;
drop sequence SAccntTrggrLst;
drop table AccntTrggrLst cascade constraints;
drop sequence SDbtGrntLst;
drop table DbtGrntLst cascade constraints;
drop sequence SAccnt;
drop table Accnt cascade constraints;
drop sequence SDbTrNtExec;
drop table DbTrNtExec cascade constraints;
drop sequence SChngCrrncCMD;
drop table ChngCrrncCMD cascade constraints;
drop sequence SLmtTp;
drop table LmtTp cascade constraints;
drop sequence STrggrStt;
drop table TrggrStt cascade constraints;
drop sequence SCmpnstnLst;
drop table CmpnstnLst cascade constraints;
drop sequence SAllCmpLstPndgCmp;
drop table AllCmpLstPndgCmp cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SBnk;
drop table Bnk cascade constraints;
drop sequence SDbtTrnSucc;
drop table DbtTrnSucc cascade constraints;
drop sequence SRl;
drop table Rl cascade constraints;
drop sequence SEvntWrppr;
drop table EvntWrppr cascade constraints;
drop sequence SBnkFs;
drop table BnkFs cascade constraints;
drop sequence SAccntSrvcBnkFs;
drop table AccntSrvcBnkFs cascade constraints;
drop sequence SCmpRqLst;
drop table CmpRqLst cascade constraints;
drop sequence SSubjObs;
drop table SubjObs cascade constraints;
drop sequence SDebTransLstDbtTrnsfrs;
drop table DebTransLstDbtTrnsfrs cascade constraints;
drop sequence SCrrncMngrXchngRtGUI;
drop table CrrncMngrXchngRtGUI cascade constraints;
drop sequence SCrrncMngrExchngRts;
drop table CrrncMngrExchngRts cascade constraints;
drop sequence SCrrncMngrCrrncStck;
drop table CrrncMngrCrrncStck cascade constraints;
drop sequence SDbTrNtTmplTmplts;
drop table DbTrNtTmplTmplts cascade constraints;
drop sequence STrggrLstTrggrs;
drop table TrggrLstTrggrs cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SAccntDebTrfTransObs;
drop table AccntDebTrfTransObs cascade constraints;
drop sequence SDbtTrnsfrNxtdtttrg;
drop table DbtTrnsfrNxtdtttrg cascade constraints;
drop sequence SCmpnstnPndngRqstsObs;
drop table CmpnstnPndngRqstsObs cascade constraints;
drop sequence SAdmnstrtrBnksObs;
drop table AdmnstrtrBnksObs cascade constraints;
drop sequence SDbtGrntLstDbtGrnts;
drop table DbtGrntLstDbtGrnts cascade constraints;
drop sequence STrggrRls;
drop table TrggrRls cascade constraints;
drop sequence SDbTrNtExecNtExctds;
drop table DbTrNtExecNtExctds cascade constraints;
drop sequence SCmpnstnLstCmpnstns;
drop table CmpnstnLstCmpnstns cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SBnkAccnts;
drop table BnkAccnts cascade constraints;
drop sequence SDbtTrnSuccSccssfls;
drop table DbtTrnSuccSccssfls cascade constraints;
drop sequence SCmpRqLstRqsts;
drop table CmpRqLstRqsts cascade constraints;
