drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SCrtCmpnntCMD;
drop table CrtCmpnntCMD cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SPrtsLstMngr;
drop table PrtsLstMngr cascade constraints;
drop sequence SQPrt;
drop table QPrt cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SAddCmpnntCMD;
drop table AddCmpnntCMD cascade constraints;
drop sequence SMtrllst;
drop table Mtrllst cascade constraints;
drop sequence SStt;
drop table Stt cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SMtrllstVl;
drop table MtrllstVl cascade constraints;
drop sequence SCmpnnt;
drop table Cmpnnt cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
drop sequence SPrdctPrts;
drop table PrdctPrts cascade constraints;
drop sequence SSrvrCmpnnts;
drop table SrvrCmpnnts cascade constraints;
drop sequence SMtrllstVls;
drop table MtrllstVls cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
